name: flutter_template
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  dio: ^5.8.0+1
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  flutter_secure_storage: ^9.2.4
  go_router: ^15.1.1
  intl: any
  riverpod_annotation: ^2.6.1

dev_dependencies:
  build_runner: ^2.4.13
  custom_lint: ^0.7.0
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  riverpod_generator: ^2.6.3

flutter:
  uses-material-design: true
  generate: true
  fonts:
  - family: Lato
    fonts:
    - asset: assets/fonts/roboto-regular.ttf
  assets:
    - .env
    - assets/
